[package]
name = "activity-me"
version = "0.1.0"
authors = ["Philippe Gaultier <philippe.gaultier@ppro.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
regex = "1.4.5"
